"""Print models/runtimes.toml for a llama.cpp release tag (see update-llama-pin.sh)."""
import json
import sys
import urllib.request

tag = sys.argv[1]
url = f"https://api.github.com/repos/ggml-org/llama.cpp/releases/tags/{tag}"
with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "veyra-scripts"})) as r:
    rel = json.load(r)
assets = {a["name"]: a for a in rel["assets"]}
wanted = [
    ("macos", "aarch64", "metal", f"llama-{tag}-bin-macos-arm64.tar.gz", None),
    ("macos", "x86_64", "cpu", f"llama-{tag}-bin-macos-x64.tar.gz", None),
    ("linux", "x86_64", "cpu", f"llama-{tag}-bin-ubuntu-x64.tar.gz", None),
    ("linux", "x86_64", "vulkan", f"llama-{tag}-bin-ubuntu-vulkan-x64.tar.gz", None),
    ("linux", "x86_64", "cuda", f"llama-{tag}-bin-ubuntu-cuda-12.8-x64.tar.gz", None),
    ("linux", "x86_64", "rocm", f"llama-{tag}-bin-ubuntu-rocm-10.0-x64.tar.gz", None),
    ("linux", "aarch64", "cpu", f"llama-{tag}-bin-ubuntu-arm64.tar.gz", None),
    ("windows", "x86_64", "cpu", f"llama-{tag}-bin-win-cpu-x64.zip", None),
    ("windows", "x86_64", "vulkan", f"llama-{tag}-bin-win-vulkan-x64.zip", None),
    ("windows", "x86_64", "cuda", f"llama-{tag}-bin-win-cuda-12.4-x64.zip", "cudart-llama-bin-win-cuda-12.4-x64.zip"),
    ("windows", "aarch64", "cpu", f"llama-{tag}-bin-win-cpu-arm64.zip", None),
]


def digest(a):
    d = a.get("digest") or ""
    return d[len("sha256:"):] if d.startswith("sha256:") else None


print("# Pinned llama.cpp release; generated by scripts/update-llama-pin.sh.")
print("# Review before committing: every asset must have a sha256 digest.")
print()
print("[llama_cpp]")
print(f'tag = "{tag}"')
print('repo = "ggml-org/llama.cpp"')
print('license = "MIT"')
for os_, arch, accel, name, extra in wanted:
    a = assets.get(name)
    if not a or not digest(a):
        print(f"missing or undigested asset: {name}", file=sys.stderr)
        continue
    print()
    print("[[llama_cpp.asset]]")
    print(f'os = "{os_}"')
    print(f'arch = "{arch}"')
    print(f'accel = "{accel}"')
    print(f'name = "{name}"')
    print(f'sha256 = "{digest(a)}"')
    print(f"size = {a['size']}")
    if extra and extra in assets and digest(assets[extra]):
        print(f'extra_name = "{extra}"')
        print(f'extra_sha256 = "{digest(assets[extra])}"')
        print(f"extra_size = {assets[extra]['size']}")
